// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SidebarPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"sidebar-area\"><div class=\"sidebar\"><button class=\"tool\">Brush</button> <button class=\"tool\">Eraser</button> <button class=\"tool\">Fill</button></div><div class=\"generator\"><button id=\"generateMap\">Generate Map</button><div class=\"form-input\"><label>Octaves</label> <input type=\"range\" min=\"1\" max=\"10\" step=\"1\" value=\"4\" data-key=\"octaves\"> <input type=\"number\" id=\"field\" min=\"1\" max=\"10\" step=\"1\" value=\"4\" data-key=\"octaves\"></div><div class=\"form-input\"><label>Persistence</label> <input type=\"range\" min=\"0.1\" max=\"1\" id=\"persistence\" step=\"0.05\" value=\"0.5\" data-key=\"persistence\"> <input type=\"number\" id=\"field\" min=\"1\" max=\"3\" step=\"0.05\" value=\"0.5\" data-key=\"persistence\"></div><div class=\"form-input\"><label>Lacunarity</label> <input type=\"range\" min=\"1\" max=\"3\" id=\"lacunarity\" step=\"0.1\" value=\"2.0\" data-key=\"lacunarity\"> <input type=\"number\" id=\"field\" min=\"1\" max=\"3\" step=\"0.1\" value=\"2.0\" data-key=\"lacunarity\"></div><div class=\"form-input\"><label>Frequency</label> <input type=\"range\" min=\"0.005\" max=\"0.2\" id=\"frequency\" step=\"0.005\" value=\"0.01\" data-key=\"frequency\"> <input type=\"number\" id=\"field\" min=\"0.005\" max=\"0.2\" step=\"0.005\" value=\"0.01\" data-key=\"frequency\"></div><div class=\"form-input\"><label>Amplitude</label> <input type=\"range\" min=\"0.5\" max=\"2\" id=\"amplitude\" step=\"0.5\" value=\"1.0\" data-key=\"amplitude\"> <input type=\"number\" id=\"field\" min=\"0.5\" max=\"2\" step=\"0.5\" value=\"1.0\" data-key=\"amplitude\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
